-- MySQL Script generated by MySQL Workbench
-- Thu May 23 11:56:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spyingongames
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spyingongames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spyingongames` DEFAULT CHARACTER SET utf8 ;
USE `spyingongames` ;

-- -----------------------------------------------------
-- Table `spyingongames`.`patamar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spyingongames`.`patamar` (
  `idPatamar` INT NOT NULL,
  `nomePatamar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPatamar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spyingongames`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spyingongames`.`contas` (
  `nome` VARCHAR(500) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `quantCom` INT NOT NULL AUTO_INCREMENT,
  `idPatamar` INT NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_contas_patamar1_idx` (`idPatamar` ASC),
  CONSTRAINT `fk_contas_patamar1`
    FOREIGN KEY (`idPatamar`)
    REFERENCES `spyingongames`.`patamar` (`idPatamar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spyingongames`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spyingongames`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spyingongames`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spyingongames`.`jogos` (
  `nomeJogo` VARCHAR(500) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `jogoCategoria` INT NOT NULL,
  PRIMARY KEY (`nomeJogo`),
  INDEX `fk_jogos_categoria1_idx` (`jogoCategoria` ASC),
  CONSTRAINT `fk_jogos_categoria1`
    FOREIGN KEY (`jogoCategoria`)
    REFERENCES `spyingongames`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spyingongames`.`tabComentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spyingongames`.`tabComentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `conteudo` VARCHAR(1000) NOT NULL,
  `jogoComentado` VARCHAR(500) NOT NULL,
  `comentarioConta` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_tabComentarios_jogos_idx` (`jogoComentado` ASC),
  INDEX `fk_tabComentarios_contas1_idx` (`comentarioConta` ASC),
  CONSTRAINT `fk_tabComentarios_jogos`
    FOREIGN KEY (`jogoComentado`)
    REFERENCES `spyingongames`.`jogos` (`nomeJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabComentarios_contas1`
    FOREIGN KEY (`comentarioConta`)
    REFERENCES `spyingongames`.`contas` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;































-- atualização

-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 10:03:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema novoSistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema novoSistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `novoSistema` DEFAULT CHARACTER SET utf8 ;
USE `novoSistema` ;

-- -----------------------------------------------------
-- Table `novoSistema`.`patamar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novoSistema`.`patamar` (
  `idPatamar` INT NOT NULL,
  `nomePatamar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPatamar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `novoSistema`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novoSistema`.`contas` (
  `nome` VARCHAR(500) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `quantCom` INT NOT NULL,
  `idPatamar` INT NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_contas_patamar1_idx` (`idPatamar` ASC),
  CONSTRAINT `fk_contas_patamar1`
    FOREIGN KEY (`idPatamar`)
    REFERENCES `novoSistema`.`patamar` (`idPatamar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `novoSistema`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novoSistema`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `novoSistema`.`jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novoSistema`.`jogos` (
  `nomeJogo` VARCHAR(500) NOT NULL,
  `descricao` TEXT NOT NULL,
  `jogoCategoria` INT NOT NULL,
  `imagem` TEXT NOT NULL,
  PRIMARY KEY (`nomeJogo`),
  INDEX `fk_jogos_categoria1_idx` (`jogoCategoria` ASC),
  CONSTRAINT `fk_jogos_categoria1`
    FOREIGN KEY (`jogoCategoria`)
    REFERENCES `novoSistema`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `novoSistema`.`tabComentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `novoSistema`.`tabComentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `conteudo` TEXT NOT NULL,
  `jogoComentado` VARCHAR(500) NOT NULL,
  `comentarioConta` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_tabComentarios_jogos_idx` (`jogoComentado` ASC),
  INDEX `fk_tabComentarios_contas1_idx` (`comentarioConta` ASC),
  CONSTRAINT `fk_tabComentarios_jogos`
    FOREIGN KEY (`jogoComentado`)
    REFERENCES `novoSistema`.`jogos` (`nomeJogo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabComentarios_contas1`
    FOREIGN KEY (`comentarioConta`)
    REFERENCES `novoSistema`.`contas` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
